# Tensors

*本节介绍多种创建 tensor 的方法*

> tensor: 类似于向量但比向量更一般的数学对象，由空间坐标系中的一组函数表示。

首先加载 tensorflow 并重置计算图

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

## 启动图会话（graph session）

使用 tf.Session() 取得图句柄

In [3]:
sess = tf.Session()

## 创建 Tensors

Tensorflow 可使用內建函数创建用于变量的 tensor。例如，使用 tf.zeros() 来创建预定义形状的0值 tensor

In [5]:
my_tensor = tf.zeros([1, 20])

使用 run() 方法来对 tensor 进行评估

In [6]:
sess.run(my_tensor)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

tf 算法需要知道哪些对象是常量哪些是变量。在本章后面会解释这两者的区别。现在我们使用 tf.Variable() 创建一个变量

In [7]:
my_var = tf.Variable(tf.zeros([1, 20]))

注意，现在还不能运行 sess.run(my_var)，因为 tf 使用计算图进行计算，为了计算变量我们得先对变量进行初始化操作。后面会看到更多的这种操作。在这里，我们使用 my_var.initializer 初始化一个变量

In [9]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

为创建特定形状的变量，让我们先声明行列的大小

In [10]:
row_dim = 2
col_dim = 3

然后使用0值和1值函数声明行和列变量

In [11]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

同样的，使用初始化函数初始化变量，然后 run 来赋值它们的内容

In [13]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


## 拷贝其他 tensor 的形状来创建新 tensor

可以使用內建函数 ones_like() 或 zeros_like() 来拷贝其他 tensor 的形状

In [14]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(zero_similar.initializer)
sess.run(ones_similar.initializer)
print(sess.run(zero_similar))
print(sess.run(ones_similar))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


## 使用常量填充 tensor

👇使用常量填充 tensor

In [15]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
sess.run(fill_var)

array([[-1, -1, -1],
       [-1, -1, -1]], dtype=int32)

我们也可以从常量数组或列表创建 tensor 变量

In [16]:
# 从常量创建 tensor 变量
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# 也可用于填充数组
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


## 从序列和 Ranges 中创建 tensor

我们也可以从序列生成函数生成 tensor。tf 的 linspace() 函数和 range() 函数和 python/numpy 的操作非常相似。

In [17]:
# tf 的 linspace
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3))

# tf 的 range
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3))

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)
print(sess.run(linear_var))
print(sess.run(sequence_var))

[ 0.   0.5  1. ]
[ 6  9 12]


## 随机数字 tensor

我们也可以如下从随机数字中初始化 tensor

In [18]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)
print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[-0.24349093  0.94837433  0.25947404]
 [ 1.02237809  0.20368837  1.39328873]]
[[ 1.80642462  2.8393364   0.04007864]
 [ 1.98358107  1.11683178  0.17710972]]


## 在 TensorBoard 中可视化变量创建过程

为了能可视化变量的创建过程（第11章有更多细节），我们将重置计算图并创建一个全局的初始化操作

In [19]:
# 重置图
ops.reset_default_graph()

# 重启动会话
sess = tf.Session()

# 创建变量
my_var = tf.Variable(tf.zeros([1, 20]))

# 添加概要到 tensorboard
merged = tf.summary.merge_all()

# 初始化图 writer
writer = tf.summary.FileWriter('./variable_logs', graph=sess.graph)

# 初始化操作
initialize_op = tf.global_variables_initializer()

# 运行“初始化操作”
sess.run(initialize_op)

然后在终端运行如下命令

```
$ tensorboard --logdir=./
```

然后在打开其提示的链接，默认为 http://0.0.0.0:6006/ 将会看到 tensor 变量的初始化过程

![png](./02.png)